name: Publish Documentation

on:
  push:
    paths: 
      - documentation/**

jobs:
  main:
    name: Publish Documentation

    runs-on: ubuntu-latest

    environment:
      name: Documentation
      url: https://react-unity-webgl.jeffreylanters.nl

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.5.1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: Cache Node Module Dependencies
        uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: nodemodules-${{ runner.os }}-${{ hashFiles('./documentation/package-lock.json') }}

      - name: Install Dependencies
        working-directory: ./documentation
        run: npm install

      - name: Build Docusaurus
        working-directory: ./documentation
        run: npm run build
        
      - name: Copy Build To Server
        uses: appleboy/scp-action@v0.1.2
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_KEY_PASSPHRASE }}
          source: ./documentation/build
          target: ${{ secrets.SSH_TARGET }}
          rm: true